id = "zlang"
name = "Zlang"
version = "0.1.0"
schema_version = 1
authors = ["zlangdevs"]
description = "Zlang syntax highlighting for Zed"
repository = "https://github.com/zlangdevs/zed-zlang"

[grammars.zlang]
repository = "https://github.com/zlangdevs/zed-zlang"
rev = "65da610cef11787e41665a80f54db8f642cbee5c"
