id = "zlang"
name = "Zlang"
version = "0.1.0"
schema_version = 1
authors = ["hedgegod"]
description = "Zlang syntax highlighting for Zed"
repository = "https://github.com/zlangdevs/zed-zlang"

[grammars.zlang]
repository = "https://github.com/zlangdevs/zed-zlang"
commit = "cc587a8d36f1a2f82318383819a7b9f7b92beb54"
